import { writeFileSync, existsSync, readFileSync } from 'fs';
import path from 'path';
import { getHosts } from './hosts.js';
import { PATHS, PORTS, toApachePath, ensureDir, isWindows } from './config.js';

function existingPorts() {
  const ports = new Set([PORTS.apache]);
  const confFiles = [PATHS.apacheConf];
  
  for (const f of confFiles) {
    if (!existsSync(f)) continue;
    try {
      const content = readFileSync(f, 'utf8');
      for (const line of content.split('\n')) {
        const m = line.match(/^\s*Listen\s+(\d+)/i);
        if (m) ports.add(parseInt(m[1]));
      }
    } catch {}
  }
  return ports;
}

export function resolveDocumentRoot(baseRoot) {
  if (!baseRoot) return baseRoot;
  const publicDirs = ['public', 'public_html', 'web', 'htdocs', 'www'];
  for (const dir of publicDirs) {
    const candidate = path.join(baseRoot, dir);
    if (existsSync(candidate)) {
      if (
        existsSync(path.join(candidate, 'index.php')) ||
        existsSync(path.join(candidate, 'index.html')) ||
        existsSync(path.join(candidate, 'index.htm'))
      ) {
        return candidate;
      }
    }
  }
  return baseRoot;
}

export function generateVhostConfig() {
  const hosts = getHosts();
  const existing = existingPorts();
  const blocks = [];

  blocks.push('# =========================================================');
  blocks.push('# DDS Virtual Hosts -- Auto-generated by DDS CLI');
  blocks.push('# Generated at: ' + new Date().toISOString());
  blocks.push('# =========================================================');
  blocks.push('');

  // Add Listen directives for custom ports
  for (const host of hosts) {
    const port = parseInt(host.port);
    if (!existing.has(port)) {
      existing.add(port);
      blocks.push(`Listen ${port}`);
    }
  }

  blocks.push('');

  const logsDir = toApachePath(PATHS.logs);
  ensureDir(PATHS.logs);

  for (const host of hosts) {
    const port = host.port;
    const serverName = host.name === 'default' ? 'localhost' : `${host.name}.localhost`;
    const baseRoot = toApachePath(host.root);
    ensureDir(baseRoot);
    const docRoot = toApachePath(resolveDocumentRoot(host.root));
    if (docRoot !== baseRoot) ensureDir(docRoot);

    blocks.push(`<VirtualHost *:${port}>`);
    blocks.push(`    DocumentRoot "${docRoot}"`);
    blocks.push(`    ServerName ${serverName}`);
    blocks.push('');
    blocks.push(`    <Directory "${docRoot}">`);
    blocks.push('        Options Indexes FollowSymLinks ExecCGI');
    blocks.push('        AllowOverride All');
    blocks.push('        Require all granted');
    blocks.push('        DirectoryIndex index.php index.html index.htm');
    blocks.push('    </Directory>');
    if (docRoot !== baseRoot) {
      blocks.push('');
      blocks.push(`    <Directory "${baseRoot}">`);
      blocks.push('        Options Indexes FollowSymLinks ExecCGI');
      blocks.push('        AllowOverride All');
      blocks.push('        Require all granted');
      blocks.push('    </Directory>');
    }
    blocks.push('');
    blocks.push(`    ErrorLog "${logsDir}/${host.name}_error.log"`);
    blocks.push(`    CustomLog "${logsDir}/${host.name}_access.log" common`);
    blocks.push('</VirtualHost>');
    blocks.push('');
  }

  // SSL Virtual Hosts
  const cert = toApachePath(PATHS.sslCert);
  const key = toApachePath(PATHS.sslKey);

  if (existsSync(PATHS.sslCert) && existsSync(PATHS.sslKey)) {
    let sslPort = PORTS.apacheSsl;
    for (const host of hosts) {
      if (host.name === 'default') continue;
      sslPort++;
      while (existing.has(sslPort)) sslPort++;
      existing.add(sslPort);

      const baseRoot = toApachePath(host.root);
      const docRoot = toApachePath(resolveDocumentRoot(host.root));
      const serverName = `${host.name}.localhost`;

      blocks.push(`Listen ${sslPort}`);
      blocks.push('');
      blocks.push(`<VirtualHost *:${sslPort}>`);
      blocks.push(`    DocumentRoot "${docRoot}"`);
      blocks.push(`    ServerName ${serverName}`);
      blocks.push('');
      blocks.push('    SSLEngine on');
      blocks.push(`    SSLCertificateFile "${cert}"`);
      blocks.push(`    SSLCertificateKeyFile "${key}"`);
      blocks.push('');
      blocks.push(`    <Directory "${docRoot}">`);
      blocks.push('        Options Indexes FollowSymLinks ExecCGI');
      blocks.push('        AllowOverride All');
      blocks.push('        Require all granted');
      blocks.push('        DirectoryIndex index.php index.html index.htm');
      blocks.push('    </Directory>');
      if (docRoot !== baseRoot) {
        blocks.push('');
        blocks.push(`    <Directory "${baseRoot}">`);
        blocks.push('        Options Indexes FollowSymLinks ExecCGI');
        blocks.push('        AllowOverride All');
        blocks.push('        Require all granted');
        blocks.push('    </Directory>');
      }
      blocks.push('');
      blocks.push(`    ErrorLog "${logsDir}/${host.name}_ssl_error.log"`);
      blocks.push(`    CustomLog "${logsDir}/${host.name}_ssl_access.log" common`);
      blocks.push('</VirtualHost>');
      blocks.push('');
    }
  }

  const content = blocks.join('\n');
  const targetDir = path.dirname(PATHS.vhostConf);
  ensureDir(targetDir);
  writeFileSync(PATHS.vhostConf, content, 'utf8');
  return content;
}

export function getDefaultPort() {
  const hosts = getHosts();
  const def = hosts.find(h => h.name === 'default');
  return def ? def.port : PORTS.apache;
}
